services:
  - type: web
    name: wrike-webhook
    runtime: python
    buildCommand: ""
    startCommand: uvicorn wrike_webhook_to_webex:app --host 0.0.0.0 --port 10000
    envVars:
      - key: WEBEX_TOKEN
        sync: false

